import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/DcfV0ULMNl9mfFXWlI1YQg?node-id=334%3A90862",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      type: figma.enum("Type", {
        primary: "primary",
        Secondary: "Secondary",
        Tertiary: "Tertiary",
        Stock: "Stock",
        danger: "danger",
      }),
      size: figma.enum("Size", {
        large: "large",
        medium: "medium",
        small: "small",
        xsmall: "xsmall",
      }),
      stock: figma.enum("Stock", {
        disabled: "disabled",
        blue: "blue",
        red: "red",
        cancel: "cancel",
        correction: "correction",
      }),
      state: figma.enum("State", {
        Default: "default",
        pressed: "pressed",
        disabled: "disabled",
      }),
      leftIcon: figma.boolean("Left-icon"),
      rightIcon: figma.boolean("Right-icon"),
      // No matching props could be found for these Figma properties:
      // "righticon": figma.boolean('Right-icon'),
      // "lefticon": figma.boolean('Left-icon')
    },
    example: (props) => (
      <Button
        type={props.type}
        size={props.size}
        stock={props.stock}
        state={props.state}
        leftIcon={props.leftIcon}
        rightIcon={props.rightIcon}
      >
      {"버튼명"}
      </Button>
    ),
  },
)
